# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PVOPT.ui'
#
# Created: Tue Oct 21 10:57:08 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(924, 636)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/pvopt.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(_fromUtf8("font: 75 10pt \"MS Shell Dlg 2\";"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox_11 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_11.setGeometry(QtCore.QRect(20, 80, 891, 501))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.label = QtGui.QLabel(self.groupBox_11)
        self.label.setGeometry(QtCore.QRect(490, 40, 111, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox_11)
        self.label_2.setGeometry(QtCore.QRect(40, 40, 101, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_11)
        self.label_3.setGeometry(QtCore.QRect(40, 70, 221, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox_11)
        self.label_4.setGeometry(QtCore.QRect(490, 70, 201, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox_11)
        self.label_5.setGeometry(QtCore.QRect(490, 130, 81, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_11)
        self.label_6.setGeometry(QtCore.QRect(490, 100, 171, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_10 = QtGui.QLabel(self.groupBox_11)
        self.label_10.setGeometry(QtCore.QRect(490, 210, 131, 21))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_8 = QtGui.QLabel(self.groupBox_11)
        self.label_8.setGeometry(QtCore.QRect(40, 290, 81, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox_11)
        self.lineEdit.setGeometry(QtCore.QRect(690, 40, 151, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_11)
        self.lineEdit_2.setGeometry(QtCore.QRect(260, 40, 151, 20))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox_11)
        self.lineEdit_3.setGeometry(QtCore.QRect(260, 70, 151, 20))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.lineEdit_4 = QtGui.QLineEdit(self.groupBox_11)
        self.lineEdit_4.setGeometry(QtCore.QRect(690, 70, 151, 20))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.lineEdit_5 = QtGui.QLineEdit(self.groupBox_11)
        self.lineEdit_5.setGeometry(QtCore.QRect(690, 130, 151, 20))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.lineEdit_6 = QtGui.QLineEdit(self.groupBox_11)
        self.lineEdit_6.setGeometry(QtCore.QRect(690, 100, 151, 20))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.comboBox_2 = QtGui.QComboBox(self.groupBox_11)
        self.comboBox_2.setGeometry(QtCore.QRect(260, 280, 151, 21))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.label_12 = QtGui.QLabel(self.groupBox_11)
        self.label_12.setGeometry(QtCore.QRect(40, 100, 191, 20))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.groupBox_11)
        self.label_13.setGeometry(QtCore.QRect(40, 130, 111, 20))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.groupBox_11)
        self.label_14.setGeometry(QtCore.QRect(40, 150, 591, 41))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.groupBox_11)
        self.label_15.setGeometry(QtCore.QRect(40, 220, 131, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.comboBox = QtGui.QComboBox(self.groupBox_11)
        self.comboBox.setGeometry(QtCore.QRect(260, 220, 151, 21))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.lineEdit_8 = QtGui.QLineEdit(self.groupBox_11)
        self.lineEdit_8.setGeometry(QtCore.QRect(260, 190, 151, 21))
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.lineEdit_9 = QtGui.QLineEdit(self.groupBox_11)
        self.lineEdit_9.setGeometry(QtCore.QRect(260, 130, 151, 21))
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.label_7 = QtGui.QLabel(self.groupBox_11)
        self.label_7.setGeometry(QtCore.QRect(490, 240, 411, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lineEdit_11 = QtGui.QLineEdit(self.groupBox_11)
        self.lineEdit_11.setGeometry(QtCore.QRect(260, 250, 151, 21))
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.label_11 = QtGui.QLabel(self.groupBox_11)
        self.label_11.setGeometry(QtCore.QRect(40, 250, 181, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.lineEdit_12 = QtGui.QLineEdit(self.groupBox_11)
        self.lineEdit_12.setGeometry(QtCore.QRect(260, 100, 151, 21))
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.layoutWidget = QtGui.QWidget(self.groupBox_11)
        self.layoutWidget.setGeometry(QtCore.QRect(398, 351, 131, 31))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton = QtGui.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.groupBox = QtGui.QGroupBox(self.groupBox_11)
        self.groupBox.setGeometry(QtCore.QRect(30, 390, 811, 101))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.textEdit = QtGui.QTextEdit(self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(10, 20, 791, 71))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.lineEdit_7 = QtGui.QLineEdit(self.groupBox_11)
        self.lineEdit_7.setGeometry(QtCore.QRect(730, 280, 101, 21))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.spinBox = QtGui.QSpinBox(self.groupBox_11)
        self.spinBox.setGeometry(QtCore.QRect(690, 210, 42, 22))
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.pushButton_4 = QtGui.QPushButton(self.groupBox_11)
        self.pushButton_4.setGeometry(QtCore.QRect(840, 280, 21, 21))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.pushButton_5 = QtGui.QPushButton(self.groupBox_11)
        self.pushButton_5.setGeometry(QtCore.QRect(700, 280, 21, 21))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.comboBox_5 = QtGui.QComboBox(self.centralwidget)
        self.comboBox_5.setGeometry(QtCore.QRect(20, 40, 481, 22))
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(230, 780, 0, 23))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 20, 101, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 924, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionHow_to_use_PVOPT = QtGui.QAction(MainWindow)
        self.actionHow_to_use_PVOPT.setObjectName(_fromUtf8("actionHow_to_use_PVOPT"))
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addSeparator()
        self.menuHelp.addAction(self.actionHow_to_use_PVOPT)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_2, self.lineEdit)
        MainWindow.setTabOrder(self.lineEdit, self.lineEdit_3)
        MainWindow.setTabOrder(self.lineEdit_3, self.lineEdit_4)
        MainWindow.setTabOrder(self.lineEdit_4, self.lineEdit_12)
        MainWindow.setTabOrder(self.lineEdit_12, self.lineEdit_6)
        MainWindow.setTabOrder(self.lineEdit_6, self.lineEdit_9)
        MainWindow.setTabOrder(self.lineEdit_9, self.lineEdit_5)
        MainWindow.setTabOrder(self.lineEdit_5, self.lineEdit_8)
        MainWindow.setTabOrder(self.lineEdit_8, self.comboBox)
        MainWindow.setTabOrder(self.comboBox, self.spinBox)
        MainWindow.setTabOrder(self.spinBox, self.lineEdit_7)
        MainWindow.setTabOrder(self.lineEdit_7, self.lineEdit_11)
        MainWindow.setTabOrder(self.lineEdit_11, self.comboBox_2)
        MainWindow.setTabOrder(self.comboBox_2, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.pushButton_3)
        MainWindow.setTabOrder(self.pushButton_3, self.pushButton_5)
        MainWindow.setTabOrder(self.pushButton_5, self.pushButton_4)
        MainWindow.setTabOrder(self.pushButton_4, self.textEdit)
        MainWindow.setTabOrder(self.textEdit, self.comboBox_5)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "PVOPT", None))
        self.groupBox_11.setTitle(_translate("MainWindow", "Input needed", None))
        self.label.setText(_translate("MainWindow", "Current Stock Price", None))
        self.label_2.setText(_translate("MainWindow", "Strike Price", None))
        self.label_3.setText(_translate("MainWindow", "Risk free interest rate (in percentage)", None))
        self.label_4.setText(_translate("MainWindow", "Duration of the Option (in Years)", None))
        self.label_5.setText(_translate("MainWindow", "Volatility", None))
        self.label_6.setText(_translate("MainWindow", "Dividend Yield (in percentage)", None))
        self.label_10.setText(_translate("MainWindow", "Number of dividends ", None))
        self.label_8.setText(_translate("MainWindow", "Option type", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Select", None))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Call", None))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Put", None))
        self.label_12.setText(_translate("MainWindow", "Maturity Date as \'YYYYMMDD\'", None))
        self.label_13.setText(_translate("MainWindow", "Company\'s Symbol", None))
        self.label_14.setText(_translate("MainWindow", "Number of days of data you want to consider: Insert \'1\' for time equal to the duration of the option", None))
        self.label_15.setText(_translate("MainWindow", "Data Source", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "Select", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "Yahoo", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "Google", None))
        self.label_7.setText(_translate("MainWindow", "Time of dividends and dividends (in the order t1,D1,t2,D2,...)", None))
        self.label_11.setText(_translate("MainWindow", "Number of binomial steps", None))
        self.pushButton.setText(_translate("MainWindow", "Ok", None))
        self.pushButton_2.setText(_translate("MainWindow", "Clear", None))
        self.pushButton_3.setText(_translate("MainWindow", "Close", None))
        self.groupBox.setTitle(_translate("MainWindow", "Output", None))
        self.pushButton_4.setText(_translate("MainWindow", ">>", None))
        self.pushButton_5.setText(_translate("MainWindow", "<<", None))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "Select", None))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "European, Non-Dividend-Paying, Using Historical Data", None))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "European, Non-Dividend-Paying, Volatility Known", None))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "European, Known Dividend Yield, Modified Black Scholes, Using Historical Data", None))
        self.comboBox_5.setItemText(4, _translate("MainWindow", "European, Known Dividend Yield, Modified Black Scholes, Volatility Known", None))
        self.comboBox_5.setItemText(5, _translate("MainWindow", "European, Known Dividend Yield, Binomial Model, Using Historical Data", None))
        self.comboBox_5.setItemText(6, _translate("MainWindow", "European, Known Dividend Yield, Binomial Model, Volatility Known", None))
        self.comboBox_5.setItemText(7, _translate("MainWindow", "European, Known Cash Dividend, Bos-Vandermark, Using Historical Data", None))
        self.comboBox_5.setItemText(8, _translate("MainWindow", "European, Known Cash Dividend, Bos-Vandermark, Volatility Known", None))
        self.comboBox_5.setItemText(9, _translate("MainWindow", "European, Known Cash Dividend, Interpolated Binomial, Using Historical Data", None))
        self.comboBox_5.setItemText(10, _translate("MainWindow", "European, Known Cash Dividend, Interpolated Binomial, Volatility Known", None))
        self.comboBox_5.setItemText(11, _translate("MainWindow", "American, Non-Dividend-Paying, Using Historical Data", None))
        self.comboBox_5.setItemText(12, _translate("MainWindow", "American, Non-Dividend-Paying, Volatility Known", None))
        self.comboBox_5.setItemText(13, _translate("MainWindow", "American, Known Dividend Yield, Using Historical Data", None))
        self.comboBox_5.setItemText(14, _translate("MainWindow", "American, Known Dividend Yield, Volatility Known", None))
        self.comboBox_5.setItemText(15, _translate("MainWindow", "American, Known Cash Dividend, Using Historical Data", None))
        self.comboBox_5.setItemText(16, _translate("MainWindow", "American, Known Cash Dividend, Volatility Known", None))
        self.label_9.setText(_translate("MainWindow", "Option category", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionHow_to_use_PVOPT.setText(_translate("MainWindow", "How to use PVOPT", None))

import icon_rc



